spring.application.name=telegram-courses-platform
spring.profiles.default=dev

spring.datasource.url=jdbc:mysql://${DB_BASE_URL}/${DB_NAME}?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.open-in-view=false

tcp.base.start-bot-token=${INITIAL_BOT_TOKEN}
tcp.base.bot-lord-token=${BOT_LORD_TOKEN}
tcp.base.director-id=${DIRECTOR_ID}

tcp.localizations.path=localizations
tcp.localizations.format=.txt
tcp.localizations.language-priority=en, ru

tcp.webhook.secret=${WEBHOOK_SECRET}

tcp.invoice.images.path=invoice/images
