logging.level.com.unbidden.telegramcoursesbot=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true

tcp.scheduling.auto-clearing.delay=120000
tcp.scheduling.timed-trigger.delay=60000
tcp.scheduling.session.expiration=600
tcp.scheduling.multipage-meta.expiration=600
tcp.scheduling.review-session.expiration=600
tcp.scheduling.feedback-session.expiration=600

tcp.paged-request.reviews.page-size=3
tcp.paged-request.homework.page-size=3

tcp.webhook.url=https://4dad-143-244-46-121.ngrok-free.app
tcp.webhook.ip=
tcp.webhook.max-connections=40
tcp.webhook.use-certificate=false

tcp.exception.inform-director=false

server.port=8080
